// Modifications copyright (C) 2024 Chair of Electronic Design Automation, TUM
/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void test_depthwise_int4_1_muriscv_nn_depthwise_conv_s4_opt(void);
extern void test_depthwise_int4_2_muriscv_nn_depthwise_conv_s4_opt(void);
extern void test_depthwise_int4_3_muriscv_nn_depthwise_conv_s4_opt(void);
extern void test_depthwise_int4_4_muriscv_nn_depthwise_conv_s4_opt(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
//#ifdef UNITY_USE_COMMAND_LINE_ARGS
//    if (!UnityTestMatches())
//        return;
//#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestCases/test_muriscv_nn_depthwise_conv_s4_opt/Unity/unity_test_muriscv_nn_depthwise_conv_s4_opt.c");
  run_test(test_depthwise_int4_1_muriscv_nn_depthwise_conv_s4_opt, "test_depthwise_int4_1_muriscv_nn_depthwise_conv_s4_opt", 47);
  run_test(test_depthwise_int4_2_muriscv_nn_depthwise_conv_s4_opt, "test_depthwise_int4_2_muriscv_nn_depthwise_conv_s4_opt", 48);
  run_test(test_depthwise_int4_3_muriscv_nn_depthwise_conv_s4_opt, "test_depthwise_int4_3_muriscv_nn_depthwise_conv_s4_opt", 49);
  run_test(test_depthwise_int4_4_muriscv_nn_depthwise_conv_s4_opt, "test_depthwise_int4_4_muriscv_nn_depthwise_conv_s4_opt", 50);

  return UnityEnd();
}
