// Modifications copyright (C) 2024 Chair of Electronic Design Automation, TUM
// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t avgpooling_1_output_ref[3] = {5, 14, -5};
