// Modifications copyright (C) 2024 Chair of Electronic Design Automation, TUM
/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void test_kernel1x1_muriscv_nn_convolve_1x1_s8_fast(void);
extern void test_kernel1x1_stride_x_muriscv_nn_convolve_1x1_s8(void);
extern void test_kernel1x1_stride_x_y_muriscv_nn_convolve_1x1_s8(void);
extern void test_kernel1x1_stride_x_y_1_muriscv_nn_convolve_1x1_s8(void);
extern void test_kernel1x1_stride_x_y_2_muriscv_nn_convolve_1x1_s8(void);
extern void test_buffer_size_muriscv_nn_convolve_1x1_s8_fast(void);
extern void test_buffer_size_mve_muriscv_nn_convolve_1x1_s8_fast(void);
extern void test_buffer_size_dsp_muriscv_nn_convolve_1x1_s8_fast(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
//#ifdef UNITY_USE_COMMAND_LINE_ARGS
//    if (!UnityTestMatches())
//        return;
//#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestCases/test_muriscv_nn_convolve_1x1_s8_fast/Unity/unity_test_muriscv_nn_convolve_1x1_s8_fast.c");
  run_test(test_kernel1x1_muriscv_nn_convolve_1x1_s8_fast, "test_kernel1x1_muriscv_nn_convolve_1x1_s8_fast", 47);
  run_test(test_kernel1x1_stride_x_muriscv_nn_convolve_1x1_s8, "test_kernel1x1_stride_x_muriscv_nn_convolve_1x1_s8", 48);
  run_test(test_kernel1x1_stride_x_y_muriscv_nn_convolve_1x1_s8, "test_kernel1x1_stride_x_y_muriscv_nn_convolve_1x1_s8", 49);
  run_test(test_kernel1x1_stride_x_y_1_muriscv_nn_convolve_1x1_s8, "test_kernel1x1_stride_x_y_1_muriscv_nn_convolve_1x1_s8", 50);
  run_test(test_kernel1x1_stride_x_y_2_muriscv_nn_convolve_1x1_s8, "test_kernel1x1_stride_x_y_2_muriscv_nn_convolve_1x1_s8", 51);
  run_test(test_buffer_size_muriscv_nn_convolve_1x1_s8_fast, "test_buffer_size_muriscv_nn_convolve_1x1_s8_fast", 52);
  run_test(test_buffer_size_mve_muriscv_nn_convolve_1x1_s8_fast, "test_buffer_size_mve_muriscv_nn_convolve_1x1_s8_fast", 53);
  run_test(test_buffer_size_dsp_muriscv_nn_convolve_1x1_s8_fast, "test_buffer_size_dsp_muriscv_nn_convolve_1x1_s8_fast", 54);

  return UnityEnd();
}
