// Modifications copyright (C) 2024 Chair of Electronic Design Automation, TUM
// Generated by generate_test_data.py using TFL version 2.6.0 as reference.
#pragma once
#include <stdint.h>

const int8_t maxpooling_1_output_ref[3] = {122, 126, 120};
