// Modifications copyright (C) 2024 Chair of Electronic Design Automation, TUM
/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void test_basic_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_depthwise_eq_in_out_ch_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_depthwise_sub_block_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_depthwise_out_activation_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_depthwise_null_bias_0_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_depthwise_x_stride_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_buffer_size_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_buffer_size_mve_muriscv_nn_depthwise_conv_s8_opt(void);
extern void test_buffer_size_dsp_muriscv_nn_depthwise_conv_s8_opt(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}
/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
//#ifdef UNITY_USE_COMMAND_LINE_ARGS
//    if (!UnityTestMatches())
//        return;
//#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {

            setUp();
            func();

    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestCases/test_muriscv_nn_depthwise_conv_s8_opt/Unity/unity_test_muriscv_nn_depthwise_conv_s8_opt.c");
  run_test(test_basic_muriscv_nn_depthwise_conv_s8_opt, "test_basic_muriscv_nn_depthwise_conv_s8_opt", 47);
  run_test(test_depthwise_eq_in_out_ch_muriscv_nn_depthwise_conv_s8_opt, "test_depthwise_eq_in_out_ch_muriscv_nn_depthwise_conv_s8_opt", 49);
  run_test(test_depthwise_sub_block_muriscv_nn_depthwise_conv_s8_opt, "test_depthwise_sub_block_muriscv_nn_depthwise_conv_s8_opt", 51);
  run_test(test_depthwise_out_activation_muriscv_nn_depthwise_conv_s8_opt, "test_depthwise_out_activation_muriscv_nn_depthwise_conv_s8_opt", 53);
  run_test(test_depthwise_null_bias_0_muriscv_nn_depthwise_conv_s8_opt, "test_depthwise_null_bias_0_muriscv_nn_depthwise_conv_s8_opt", 58);
  run_test(test_depthwise_x_stride_muriscv_nn_depthwise_conv_s8_opt, "test_depthwise_x_stride_muriscv_nn_depthwise_conv_s8_opt", 60);
  run_test(test_buffer_size_muriscv_nn_depthwise_conv_s8_opt, "test_buffer_size_muriscv_nn_depthwise_conv_s8_opt", 62);
  run_test(test_buffer_size_mve_muriscv_nn_depthwise_conv_s8_opt, "test_buffer_size_mve_muriscv_nn_depthwise_conv_s8_opt", 64);
  run_test(test_buffer_size_dsp_muriscv_nn_depthwise_conv_s8_opt, "test_buffer_size_dsp_muriscv_nn_depthwise_conv_s8_opt", 66);

  return UnityEnd();
}
